version: '3.0'
services:
    rasa:
        image: rasa_bashbot:latest
        ports:
            - 5005:5005
        command:
            - run
            - --cors
            - "*"
    action:
        image: action_server:latest
        expose: 
            - 5055
    #duckling:
    #    image: rasa/duckling
    #    ports:
    #        - 8000:8000
    webclient:
        image: webclient:latest
        ports:
            - 80:80
    api-gw:
        image: api_gw:latest
        ports:
            - 3000:3000